### ISSUE TITLE
cf push - yaml: line 7: did not find expected key

### ISSUE THREAD

**Issue by cool1122** [watson-developer-cloud/conversation-simple#125]
Getting YAML: line 7: did not find the expected key issue when trying to push to bluemix.
Working fine in local

This is the content of my manifest.yml file
```yml
---
declared-services:
 Conversation-r7:
   label: conversation
   plan: free
applications:
- name: conversation-simple-app-test1
 command: npm start
 path: .
 memory: 256M
 instances: 1
 services:
 - Conversation-r7
 env:
   NPM_CONFIG_PRODUCTION: false
```

`Conversation-r7` is the service name. Have also run 
```
cf create-service-key Conversation-r7 myKey
```
 to create a key as described. It's working fine in local
